import sys
import copy
import json
import torch
import random
import numpy as np
import argparse
import os
from sklearn.preprocessing import MultiLabelBinarizer
from transformers import T5ForConditionalGeneration
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, confusion_matrix
from tqdm import tqdm
from transformers import LogitsProcessor, LogitsProcessorList
from transformers import T5Tokenizer, T5Config, AdamW
from torch.nn.parallel import DistributedDataParallel as DDP
from transformers.optimization import get_linear_schedule_with_warmup
# from transformers import AdapterConfig, AdapterType
from torch.utils.data import Dataset, DataLoader, DistributedSampler, random_split
from collections import Counter
import time
import warnings

random.seed(1234)
warnings.filterwarnings("ignore")


class YesNoLogitsProcessor(LogitsProcessor):
    def __init__(self, tokenizer):
        self.yes_token_id = tokenizer.convert_tokens_to_ids("Yes")
        self.no_token_id = tokenizer.convert_tokens_to_ids("No")

    def __call__(self, input_ids, scores):
        mask = torch.ones_like(scores) * float("-inf")
        mask[:, self.yes_token_id] = 0
        mask[:, self.no_token_id] = 0
        return scores + mask


relation_list = ['country of citizenship', 'date of birth', 'place of birth', 'participant of',
                 'located in the administrative territorial entity', 'contains administrative territorial entity',
                 'participant', 'location', 'followed by', 'country', 'educated at', 'date of death', 'sibling',
                 'head of government', 'legislative body', 'conflict', 'applies to jurisdiction', 'instance of',
                 'performer', 'publication date', 'creator', 'author', 'composer', 'lyrics by', 'member of',
                 'notable work', 'inception', 'part of', 'cast member', 'director', 'has part', 'production company',
                 'owned by', 'headquarters location', 'developer', 'manufacturer', 'country of origin', 'publisher',
                 'parent organization', 'subsidiary', 'capital of', 'capital', 'spouse', 'father', 'child', 'religion',
                 'mother', 'located in or next to body of water', 'located on terrain feature', 'basin country',
                 'member of political party', 'mouth of the watercourse', 'place of death', 'military branch',
                 'work location', 'start time', 'award received', 'point in time', 'founded by', 'employer',
                 'head of state', 'member of sports team', 'league', 'present in work', 'position held', 'chairperson',
                 'languages spoken, written or signed', 'location of formation', 'operator', 'producer', 'record label',
                 'follows', 'replaced by', 'replaces', 'end time', 'subclass of', 'residence', 'sister city',
                 'original network', 'ethnic group', 'separated from', 'screenwriter', 'continent', 'platform',
                 'product or material produced', 'genre', 'series', 'narrative location', 'parent taxon',
                 'original language of work', 'dissolved, abolished or demolished', 'territory claimed by',
                 'characters', 'influenced by', 'official language', 'unemployment rate']

relation_vf_templates = {
    'country of citizenship': "In the sentence '{s[sentence]}', is it correct that the country of citizenship of {s[head]} is {s[vote_answer]}? Answer :",
    'date of birth': "In the sentence '{s[sentence]}', is it correct that the date of birth of {s[head]} is {s[tail]}? Answer :",
    'place of birth': "In the sentence '{s[sentence]}', is it correct that the place of birth of {s[head]} is {s[tail]}? Answer :",
    'participant of': "Based on the sentence '{s[sentence]}', does {s[head]} participate in {s[tail]}? Answer:",
    'located in the administrative territorial entity': "In the sentence '{s[sentence]}', is it correct that {s[head]} is located in the administrative territorial entity {s[tail]}? Answer :",
    'contains administrative territorial entity': "In the sentence '{s[sentence]}', is it correct that {s[head]} contains the administrative territorial entity {s[tail]}? Answer :",
    'participant': "In the sentence '{s[sentence]}', is it correct that {s[head]} is a participant in {s[tail]}? Answer :",
    'location': "In the sentence '{s[sentence]}', is it correct that the location of {s[head]} is {s[tail]}? Answer :",
    'followed by': "In the sentence '{s[sentence]}', is it correct that {s[head]} is followed by {s[tail]}? Answer :",
    'country': "In the sentence '{s[sentence]}', is it correct that {s[head]} is a country of {s[tail]}? Answer :",
    'educated at': "In the sentence '{s[sentence]}', is it correct that {s[head]} was educated at {s[tail]}? Answer :",
    'date of death': "In the sentence '{s[sentence]}', is it correct that the date of death of {s[head]} is {s[tail]}? Answer :",
    'sibling': "In the sentence '{s[sentence]}', is it correct that {s[head]} is a sibling of {s[tail]}? Answer :",
    'head of government': "In the sentence '{s[sentence]}', is it correct that {s[head]} is the head of government of {s[tail]}? Answer :",
    'legislative body': "In the sentence '{s[sentence]}', is it correct that {s[head]} is a legislative body of {s[tail]}? Answer :",
    'conflict': "In the sentence '{s[sentence]}', is it correct that there was a conflict between {s[head]} and {s[tail]}? Answer :",
    'applies to jurisdiction': "In the sentence '{s[sentence]}', is it correct that the jurisdiction of {s[head]} applies to {s[tail]}? Answer :",
    'instance of': "In the sentence '{s[sentence]}', is it correct that {s[head]} is an instance of {s[tail]}? Answer :",
    'performer': "In the sentence '{s[sentence]}', is it correct that {s[head]} is a performer in {s[tail]}? Answer :",
    'publication date': "In the sentence '{s[sentence]}', is it correct that {s[head]} was published on {s[tail]}? Answer :",
    'creator': "In the sentence '{s[sentence]}', is it correct that {s[head]} was created by {s[tail]}? Answer :",
    'author': "In the sentence '{s[sentence]}', is it correct that {s[head]} was authored by {s[tail]}? Answer :",
    'composer': "In the sentence '{s[sentence]}', is it correct that {s[head]} was composed by {s[tail]}? Answer :",
    'lyrics by': "In the sentence '{s[sentence]}', is it correct that the lyrics of {s[head]} were written by {s[tail]}? Answer :",
    'member of': "In the sentence '{s[sentence]}', is it correct that {s[head]} is a member of {s[tail]}? Answer :",
    'notable work': "In the sentence '{s[sentence]}', is it correct that {s[head]} is a notable work of {s[tail]}? Answer :",
    'inception': "In the sentence '{s[sentence]}', is it correct that {s[head]} was founded or started on {s[tail]}? Answer :",
    'part of': "In the sentence '{s[sentence]}', is it correct that {s[head]} is a part of {s[tail]}? Answer :",
    'cast member': "In the sentence '{s[sentence]}', is it correct that {s[head]} is a cast member in {s[tail]}? Answer :",
    'director': "In the sentence '{s[sentence]}', is it correct that {s[head]} was directed by {s[tail]}? Answer :",
    'has part': "In the sentence '{s[sentence]}', is it correct that {s[head]} has {s[tail]} as a part? Answer :",
    'production company': "In the sentence '{s[sentence]}', is it correct that the production company of {s[head]} is {s[tail]}? Answer :",
    'owned by': "In the sentence '{s[sentence]}', is it correct that {s[head]} is owned by {s[tail]}? Answer :",
    'headquarters location': "In the sentence '{s[sentence]}', is it correct that the headquarters of {s[head]} is located in {s[tail]}? Answer :",
    'developer': "In the sentence '{s[sentence]}', is it correct that {s[head]} was developed by {s[tail]}? Answer :",
    'manufacturer': "In the sentence '{s[sentence]}', is it correct that {s[head]} is manufactured by {s[tail]}? Answer :",
    'country of origin': "In the sentence '{s[sentence]}', is it correct that the country of origin for {s[head]} is {s[tail]}? Answer :",
    'publisher': "In the sentence '{s[sentence]}', is it correct that {s[head]} is published by {s[tail]}? Answer :",
    'parent organization': "In the sentence '{s[sentence]}', is it correct that the parent organization of {s[head]} is {s[tail]}? Answer :",
    'subsidiary': "In the sentence '{s[sentence]}', is it correct that {s[head]} is a subsidiary of {s[tail]}? Answer :",
    'capital of': "In the sentence '{s[sentence]}', is it correct that {s[head]} is the capital of {s[tail]}? Answer :",
    'capital': "In the sentence '{s[sentence]}', is it correct that {s[head]} is the capital of {s[tail]}? Answer :",
    'spouse': "In the sentence '{s[sentence]}', is it correct that {s[head]} is married to {s[tail]}? Answer :",
    'father': "In the sentence '{s[sentence]}', is it correct that {s[head]}'s father is {s[tail]}? Answer :",
    'child': "In the sentence '{s[sentence]}', is it correct that {s[head]} is the child of {s[tail]}? Answer :",
    'religion': "In the sentence '{s[sentence]}', is it correct that {s[head]}'s religion is {s[tail]}? Answer :",
    'mother': "In the sentence '{s[sentence]}', is it correct that {s[head]}'s mother is {s[tail]}? Answer :",
    'located in or next to body of water': "In the sentence '{sentence}', is it correct that {head} is located in or next to the body of water {tail}? Answer :",
    'located on terrain feature': "In the sentence '{sentence}', is it correct that {head} is located on the terrain feature {tail}? Answer :",
    'basin country': "In the sentence '{sentence}', is it correct that {head} is a basin country of {tail}? Answer :",
    'member of political party': "In the sentence '{sentence}', is it correct that {head} is a member of the political party {tail}? Answer :",
    'mouth of the watercourse': "In the sentence '{sentence}', is it correct that the mouth of the watercourse {head} is {tail}? Answer :",
    'place of death': "In the sentence '{sentence}', is it correct that {head} died in {tail}? Answer :",
    'military branch': "In the sentence '{sentence}', is it correct that {head} is a part of the military branch {tail}? Answer :",
    'work location': "In the sentence '{sentence}', is it correct that {head} works in {tail}? Answer :",
    'start time': "In the sentence '{sentence}', is it correct that the start time of {head} is {tail}? Answer :",
    'award received': "In the sentence '{sentence}', is it correct that {head} received the award {tail}? Answer :",
    'point in time': "In the sentence '{sentence}', is it correct that {head} happened at {tail}? Answer :",
    'founded by': "In the sentence '{sentence}', is it correct that {head} was founded by {tail}? Answer :",
    'employer': "In the sentence '{sentence}', is it correct that {head} is the employer of {tail}? Answer :",
    'head of state': "In the sentence '{sentence}', is it correct that {head} is the head of state of {tail}? Answer :",
    'member of sports team': "In the sentence '{sentence}', is it correct that {head} is a member of the sports team {tail}? Answer :",
    'league': "In the sentence '{sentence}', is it correct that {head} is part of the league {tail}? Answer :",
    'present in work': "In the sentence '{sentence}', is it correct that {head} is present in the work {tail}? Answer :",
    'position held': "In the sentence '{s[sentence]}', is it correct that the position held by {s[head]} is {s[tail]}? Answer :",
    'chairperson': "In the sentence '{s[sentence]}', is it correct that the chairperson of {s[head]} is {s[tail]}? Answer :",
    'languages spoken, written or signed': "In the sentence '{s[sentence]}', is it correct that {s[head]} speaks, writes, or signs {s[tail]}? Answer :",
    'location of formation': "In the sentence '{s[sentence]}', is it correct that {s[head]} was formed in {s[tail]}? Answer :",
    'operator': "In the sentence '{s[sentence]}', is it correct that the operator of {s[head]} is {s[tail]}? Answer :",
    'producer': "In the sentence '{s[sentence]}', is it correct that the producer of {s[head]} is {s[tail]}? Answer :",
    'record label': "In the sentence '{s[sentence]}', is it correct that the record label of {s[head]} is {s[tail]}? Answer :",
    'follows': "In the sentence '{s[sentence]}', is it correct that {s[head]} follows {s[tail]}? Answer :",
    'replaced by': "In the sentence '{s[sentence]}', is it correct that {s[head]} is replaced by {s[tail]}? Answer :",
    'replaces': "In the sentence '{s[sentence]}', is it correct that {s[head]} replaces {s[tail]}? Answer :",
    'end time': "In the sentence '{s[sentence]}', is it correct that the end time of {s[head]} is {s[tail]}? Answer :",
    'subclass of': "In the sentence '{s[sentence]}', is it correct that {s[head]} is a subclass of {s[tail]}? Answer :",
    'residence': "In the sentence '{s[sentence]}', is it correct that the residence of {s[head]} is {s[tail]}? Answer :",
    'sister city': "In the sentence '{s[sentence]}', is it correct that the sister city of {s[head]} is {s[tail]}? Answer :",
    'original network': "In the sentence '{s[sentence]}', is it correct that the original network of {s[head]} is {s[tail]}? Answer :",
    'ethnic group': "In the sentence '{s[sentence]}', is it correct that the ethnic group of {s[head]} is {s[tail]}? Answer :",
    'separated from': "In the sentence '{s[sentence]}', is it correct that {s[head]} is separated from {s[tail]}? Answer :",
    'screenwriter': "In the sentence '{s[sentence]}', is it correct that the screenwriter of {s[head]} is {s[tail]}? Answer :",
    'continent': "In the sentence '{s[sentence]}', is it correct that the continent of {s[head]} is {s[tail]}? Answer :",
    'platform': "In the sentence '{s[sentence]}', is it correct that the platform of {s[head]} is {s[tail]}? Answer :",
    'product or material produced': "In the sentence '{s[sentence]}', is it correct that {s[head]} produces {s[tail]} as a product or material? Answer :",
    'genre': "In the sentence '{s[sentence]}', is it correct that the genre of {s[head]} is {s[tail]}? Answer :",
    'series': "In the sentence '{s[sentence]}', is it correct that {s[head]} is a part of the {s[tail]} series? Answer :",
    'narrative location': "In the sentence '{s[sentence]}', is it correct that the narrative location of {s[head]} is {s[tail]}? Answer :",
    'parent taxon': "In the sentence '{s[sentence]}', is it correct that the parent taxon of {s[head]} is {s[tail]}? Answer :",
    'original language of work': "In the sentence '{s[sentence]}', is it correct that the original language of {s[head]} is {s[tail]}? Answer :",
    'dissolved, abolished or demolished': "In the sentence '{s[sentence]}', is it correct that {s[head]} was dissolved, abolished, or demolished by {s[tail]}? Answer :",
    'territory claimed by': "In the sentence '{s[sentence]}', is it correct that the territory of {s[head]} is claimed by {s[tail]}? Answer :",
    'characters': "In the sentence '{s[sentence]}', is it correct that {s[head]} has {s[tail]} characters? Answer :",
    'influenced by': "In the sentence '{s[sentence]}', is it correct that {s[head]} is influenced by {s[tail]}? Answer :",
    'official language': "In the sentence '{s[sentence]}', is it correct that the official language of {s[head]} is {s[tail]}? Answer :",
    'unemployment rate': "In the sentence '{s[sentence]}', is it correct that the unemployment rate of {s[head]} is {s[tail]}? Answer :",
    'test': "In the sentence '{s[sentence]}', is it correct that the unemployment rate of {s[head]} is {s[tail]}? Answer :",
}

relation_gen_templates = {
    'country of citizenship': "Considering the statement '{s[sentence]}', what is the country of citizenship for {s[head]}? Answer :",
    'date of birth': "From the information in '{s[sentence]}', what is the date of birth for {s[head]}? Answer :",
    "place of birth": "In the context of '{s[sentence]}', where was {s[head]} born? Answer :",
    "participant of": "According to the passage '{s[sentence]}', which event did {s[head]} participate in? Answer :",
    "located in the administrative territorial entity": "Given '{s[sentence]}', in which administrative territorial entity is {s[head]} located? Answer :",
    "contains administrative territorial entity": "Based on the text '{s[sentence]}', which administrative territorial entity is contained within {s[head]}? Answer :",
    "participant": "With the information from '{s[sentence]}', who participated in {s[head]}? Answer :",
    "location": "From the details in '{s[sentence]}', where is {s[head]} located? Answer :",
    "followed by": "Considering the statement '{s[sentence]}', which entity follows {s[head]}? Answer :",
    "country": "In light of the information '{s[sentence]}', what is the country of {s[head]}? Answer :",
    "educated at": "According to the passage '{s[sentence]}', where did {s[head]} receive their education? Answer :",
    "date of death": "From the context of '{s[sentence]}', when did {s[head]} pass away? Answer :",
    "sibling": "In the context of '{s[sentence]}', who is {s[head]}'s sibling? Answer :",
    "head of government": "Based on the text '{s[sentence]}', who is the head of government in {s[head]}? Answer :",
    "legislative body": "From the details in '{s[sentence]}', what is the legislative body of {s[head]}?  Answer :",
    "conflict": "Considering the statement '{s[sentence]}', which conflict did {s[head]} take part in? Answer :",
    "applies to jurisdiction": "Given '{s[sentence]}', to which jurisdiction does {s[head]} apply? Answer :",
    "instance of": "According to the passage '{s[sentence]}', what is {s[head]} an instance of? Answer :",
    "performer": "From the information in '{s[sentence]}', who is the performer of {s[head]}? Answer :",
    "publication date": "In light of the information '{s[sentence]}', when was {s[head]} published? Answer :",
    "creator": "In the context of '{s[sentence]}', who is the creator of {s[head]}? Answer :",
    "author": "Based on the text '{s[sentence]}', who is the author of {s[head]}? Answer :",
    "composer": "From the details in '{s[sentence]}', who is the composer of {s[head]}? Answer :",
    "lyrics by": "Considering the sentence '{s[sentence]}', please determine: the lyrics of {s[head]} are by? Answer :",
    "member of": "In the context of the sentence '{s[sentence]}', identify: {s[head]} is a member of? Answer :",
    "notable work": "Given the sentence '{s[sentence]}', please answer: a notable work of {s[head]} is? Answer :",
    "inception": "From the sentence '{s[sentence]}', deduce: the inception of {s[head]} is? Answer :",
    "part of": "Based on the sentence '{s[sentence]}', find out: {s[head]} is part of? Answer :",
    "cast member": "Using the sentence '{s[sentence]}', please determine: {s[head]} is a cast member in? Answer :",
    "director": "Given the sentence '{s[sentence]}', please answer: {s[head]} is the director of? Answer :",
    "has part": "According to the sentence '{s[sentence]}', state: {s[head]} has a part called? Answer :",
    "production company": "With reference to the sentence '{s[sentence]}', please identify: the production company of {s[head]} is? Answer :",
    "owned by": "Based on the sentence '{s[sentence]}', find out: {s[head]} is owned by? Answer :",
    "headquarters location": "Considering the sentence '{s[sentence]}', please determine: the headquarters location of {s[head]} is? Answer :",
    "developer": "From the sentence '{s[sentence]}', deduce: the developer of {s[head]} is? Answer :",
    "manufacturer": "Given the sentence '{s[sentence]}', please answer: the manufacturer of {s[head]} is? Answer :",
    "country of origin": "In the context of the sentence '{s[sentence]}', identify: the country of origin of {s[head]} is? Answer :",
    "publisher": "Using the sentence '{s[sentence]}', please determine: the publisher of {s[head]} is? Answer :",
    "parent organization": "According to the sentence '{s[sentence]}', state: the parent organization of {s[head]} is? Answer :",
    'subsidiary': "From the provided information '{s[sentence]}', identify the subsidiary of {s[head]}. Answer :",
    'capital of': "Based on the statement '{s[sentence]}', what is the capital of {s[head]}? Answer :",
    'capital': "In the context of '{s[sentence]}', which city is the capital of {s[head]}? Answer :",
    'spouse': "Considering the text '{s[sentence]}', who is the spouse of {s[head]}? Answer :",
    'father': "From the given sentence '{s[sentence]}', determine the father of {s[head]}. Answer :",
    'child': "With the information in '{s[sentence]}', who is a child of {s[head]}? Answer :",
    'religion': "Based on the excerpt '{s[sentence]}', what is the religion of {s[head]}? Answer :",
    'mother': "Using the provided details in '{s[sentence]}', identify the mother of {s[head]}. Answer :",
    'located in or next to body of water': "Given the context in '{s[sentence]}', which body of water is {s[head]} located in or next to? Answer :",
    'located on terrain feature': "From the information in '{s[sentence]}', what terrain feature is {s[head]} located on? Answer :",
    'basin country': "In the context of '{s[sentence]}', which country is {s[head]} part of the basin? Answer :",
    'member of political party': "Based on the statement '{s[sentence]}', which political party is {s[head]} a member of? Answer :",
    'mouth of the watercourse': "Considering the text '{s[sentence]}', where is the mouth of the watercourse {s[head]}? Answer :",
    'place of death': "From the given sentence '{s[sentence]}', where did {s[head]} die? Answer :",
    'military branch': "With the information in '{s[sentence]}', which military branch is {s[head]} a part of? Answer :",
    'work location': "Based on the excerpt '{s[sentence]}', where is the work location of {s[head]}? Answer :",
    'start time': "Using the provided details in '{s[sentence]}', when did {s[head]} start? Answer :",
    'award received': "Given the context in '{s[sentence]}', which award did {s[head]} receive? Answer :",
    'point in time': "From the information in '{s[sentence]}', at what point in time did {s[head]} occur? Answer :",
    'founded by': "In the context of '{s[sentence]}', who founded {s[head]}? Answer :",
    'employer': "Based on the statement '{s[sentence]}', who is the employer of {s[head]}? Answer :",
    'head of state': "Considering the text '{s[sentence]}', who is the head of state for {s[head]}? Answer :",
    'member of sports team': "From the given sentence '{s[sentence]}', which sports team is {s[head]} a member of? Answer :",
    'league': "With the information in '{s[sentence]}', which league is {s[head]} a part of? Answer :",
    'present in work': "Based on the excerpt '{s[sentence]}', in which work is {s[head]} present? Answer :",
    'position held': "Using the provided details in '{s[sentence]}', what position is held by {s[head]}? Answer :",
    'chairperson': "Given the context in '{s[sentence]}', who is the chairperson of {s[head]}? Answer :",
    'languages spoken, written or signed': "From the information in '{s[sentence]}', which languages are spoken, written, or signed by {s[head]}? Answer :",
    'location of formation': "In the context of '{s[sentence]}', where was {s[head]} formed? Answer :",
    'operator': "Based on the statement '{s[sentence]}', who is the operator of {s[head]}? Answer :",
    'producer': "Considering the text '{s[sentence]}', who is the producer of {s[head]}? Answer :",
    'record label': "From the given sentence '{s[sentence]}', which record label is associated with {s[head]}? Answer :",
    'follows': "With the information in '{s[sentence]}', what does {s[head]} follow? Answer :",
    'replaced by': "Based on the excerpt '{s[sentence]}', what replaced {s[head]}? Answer :",
    'replaces': "Using the provided details in '{s[sentence]}', what does {s[head]} replace? Answer :",
    'end time': "Given the context in '{s[sentence]}', when did {s[head]} end? Answer :",
    'subclass of': "From the information in '{s[sentence]}', what is {s[head]} a subclass of? Answer :",
    'residence': "In the context of '{s[sentence]}', where is the residence of {s[head]}? Answer :",
    'sister city': "Based on the statement '{s[sentence]}', which city is a sister city of {s[head]}? Answer :",
    'original network': "Considering the text '{s[sentence]}', what is the original network of {s[head]}? Answer :",
    'ethnic group': "From the given sentence '{s[sentence]}', which ethnic group is {s[head]} associated with? Answer :",
    'separated from': "With the information in '{s[sentence]}', what did {s[head]} separate from? Answer :",
    'screenwriter': "Based on the excerpt '{s[sentence]}', who is the screenwriter of {s[head]}? Answer :",
    'continent': "Using the provided details in '{s[sentence]}', which continent is {s[head]} located on? Answer :",
    'platform': "Given the context in '{s[sentence]}', what platform is {s[head]} associated with? Answer :",
    'product or material produced': "From the information in '{s[sentence]}', what product or material is produced by {s[head]}? Answer :",
    'genre': "In the context of '{s[sentence]}', what genre does {s[head]} belong to? Answer :",
    'series': "Based on the statement '{s[sentence]}', which series is {s[head]} a part of? Answer :",
    'narrative location': "Considering the text '{s[sentence]}', what is the narrative location of {s[head]}? Answer :",
    'parent taxon': "From the given sentence '{s[sentence]}', what is the parent taxon of {s[head]}? Answer :",
    'original language of work': "With the information in '{s[sentence]}', what is the original language of the work {s[head]}? Answer :",
    'dissolved, abolished or demolished': "Based on the excerpt '{s[sentence]}', when was {s[head]} dissolved, abolished, or demolished? Answer :",
    'territory claimed by': "Using the provided details in '{s[sentence]}', which territory is claimed by {s[head]}? Answer :",
    'characters': "Given the context in '{s[sentence]}', which characters are associated with {s[head]}? Answer :",
    'influenced by': "From the information in'{s[sentence]}', who or what influenced {s[head]}? Answer :",
    'official language': "In the context of '{s[sentence]}', what is the official language of {s[head]}? Answer :",
    'unemployment rate': "Based on the statement '{s[sentence]}', what is the unemployment rate in {s[head]}? Answer :",
}
